In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_curve, roc_auc_score, classification_report, accuracy_score, confusion_matrix ,f1_score, precision_score, recall_score, auc
from sklearn.preprocessing import OneHotEncoder
import warnings
from sklearn.model_selection import GridSearchCV
warnings.filterwarnings("ignore")
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [3]:
train = pd.read_csv('output_070323/Hadoop_train_sliding_window.csv')
test = pd.read_csv('output_070323/Hadoop_test_sliding_window.csv')
print("Train Shape:",train.shape,"Test Shape:",test.shape)

Train Shape: (143835, 566) Test Shape: (35884, 322)


In [4]:
train.head()

cluster_0  cluster_1  cluster_2  cluster_3  cluster_4  cluster_5  \
0          0          0          0          0          0          0   
1          0          0          0          0          0          0   
2          0          0          0          0          0          0   
3          0          0          0          0          0          0   
4          0          0          0          0          0          0   

   cluster_6  cluster_7  cluster_8  cluster_9  cluster_10  cluster_11  \
0          0          0          0          0           0           0   
1          0          0          0          0           0           0   
2          0          0          0          0           0           0   
3          0          0          0          0           0           0   
4          0          0          0          0           0           0   

   cluster_12  cluster_13  cluster_14  cluster_15  cluster_16  cluster_17  \
0           0           0           0           0           1           0   
1           0           0           0           0           1           0   
2           0           0           0           0           1           0   
3           0           0           0           0           1           0   
4           0           0           0           0           1           0   

   cluster_18  cluster_19  cluster_20  cluster_21  cluster_22  cluster_23  \
0           0           0           0           1           0           0   
1           0           0           0           1           0           0   
2           0           0           0           1           0           0   
3           0           0           0           1           0           0   
4           0           0           0           1           0           0   

   cluster_24  cluster_25  cluster_26  cluster_27  cluster_28  cluster_29  \
0           0           0           0           2           0           0   
1           0           0           0           2           0           0   
2           0           0           0           2           0           0   
3           0           0           0           2           0           0   
4           0           0           0           2           0           0   

   cluster_30  cluster_31  cluster_32  cluster_33  cluster_34  cluster_35  \
0           0           1           1           3           0           3   
1           0           1           1           2           0           3   
2           0           1           1           2           0           2   
3           0           1           1           2           0           2   
4           0           1           1           2           0           2   

   cluster_36  cluster_37  cluster_38  cluster_39  cluster_40  cluster_41  \
0           0           0           0           0           1           0   
1           0           0           0           0           1           0   
2           0           0           0           0           1           0   
3           0           0           0           0           1           0   
4           0           0           0           0           1           0   

   cluster_42  cluster_43  cluster_44  cluster_45  cluster_46  cluster_47  \
0           0           0           0           0           0           0   
1           0           0           0           0           0           0   
2           0           0           0           0           0           0   
3           0           0           0           0           0           0   
4           0           0           0           0           0           0   

   cluster_48  cluster_49  cluster_50  cluster_51  cluster_52  cluster_53  \
0           0           0           0           0           0           0   
1           0           0           0           0           0           0   
2           0           0           0           0           0           0   
3           0           0           0           0  

In [5]:
train.dropna(axis = "columns",inplace=True)
train.head()

cluster_0  cluster_1  cluster_2  cluster_3  cluster_4  cluster_5  \
0          0          0          0          0          0          0   
1          0          0          0          0          0          0   
2          0          0          0          0          0          0   
3          0          0          0          0          0          0   
4          0          0          0          0          0          0   

   cluster_6  cluster_7  cluster_8  cluster_9  cluster_10  cluster_11  \
0          0          0          0          0           0           0   
1          0          0          0          0           0           0   
2          0          0          0          0           0           0   
3          0          0          0          0           0           0   
4          0          0          0          0           0           0   

   cluster_12  cluster_13  cluster_14  cluster_15  cluster_16  cluster_17  \
0           0           0           0           0           1           0   
1           0           0           0           0           1           0   
2           0           0           0           0           1           0   
3           0           0           0           0           1           0   
4           0           0           0           0           1           0   

   cluster_18  cluster_19  cluster_20  cluster_21  cluster_22  cluster_23  \
0           0           0           0           1           0           0   
1           0           0           0           1           0           0   
2           0           0           0           1           0           0   
3           0           0           0           1           0           0   
4           0           0           0           1           0           0   

   cluster_24  cluster_25  cluster_26  cluster_27  cluster_28  cluster_29  \
0           0           0           0           2           0           0   
1           0           0           0           2           0           0   
2           0           0           0           2           0           0   
3           0           0           0           2           0           0   
4           0           0           0           2           0           0   

   cluster_30  cluster_31  cluster_32  cluster_33  cluster_34  cluster_35  \
0           0           1           1           3           0           3   
1           0           1           1           2           0           3   
2           0           1           1           2           0           2   
3           0           1           1           2           0           2   
4           0           1           1           2           0           2   

   cluster_36  cluster_37  cluster_38  cluster_39  cluster_40  cluster_41  \
0           0           0           0           0           1           0   
1           0           0           0           0           1           0   
2           0           0           0           0           1           0   
3           0           0           0           0           1           0   
4           0           0           0           0           1           0   

   cluster_42  cluster_43  cluster_44  cluster_45  cluster_46  cluster_47  \
0           0           0           0           0           0           0   
1           0           0           0           0           0           0   
2           0           0           0           0           0           0   
3           0           0           0           0           0           0   
4           0           0           0           0           0           0   

   cluster_48  cluster_49  cluster_50  cluster_51  cluster_52  cluster_53  \
0           0           0           0           0           0           0   
1           0           0           0           0           0           0   
2           0           0           0           0           0           0   
3           0           0           0           0  

In [6]:
test.dropna(axis = "columns",inplace=True)
test.head()

cluster_0  cluster_1  cluster_2  cluster_3  cluster_4  cluster_5  \
0          0          0          0          0          4          0   
1          0          0          0          0          4          0   
2          0          0          0          0          4          0   
3          0          0          0          0          5          0   
4          0          0          0          0          5          0   

   cluster_6  cluster_7  cluster_8  cluster_9  cluster_10  cluster_11  \
0          0          0          0          1           0           0   
1          0          0          0          1           0           0   
2          0          0          0          1           0           0   
3          0          0          0          1           0           0   
4          0          0          0          1           0           0   

   cluster_12  cluster_13  cluster_14  cluster_15  cluster_16  cluster_17  \
0           0           3           0           0           0           0   
1           0           4           0           0           0           0   
2           0           4           0           0           0           0   
3           0           4           0           0           0           0   
4           0           4           0           0           0           0   

   cluster_18  cluster_19  cluster_20  cluster_21  cluster_22  cluster_23  \
0           0           1           1           0           0           0   
1           0           1           1           0           0           0   
2           0           1           1           0           0           0   
3           0           1           1           0           0           0   
4           0           1           1           0           0           0   

   cluster_24  cluster_25  cluster_26  cluster_27  cluster_28  cluster_29  \
0           0           4           0           0           0           0   
1           0           4           0           0           0           0   
2           0           4           0           0           0           0   
3           0           4           0           0           0           0   
4           0           4           0           0           0           0   

   cluster_30  cluster_31  cluster_32  cluster_33  cluster_34  cluster_35  \
0           5           0           0           0           0           0   
1           4           0           0           0           0           0   
2           3           0           0           0           0           0   
3           3           0           0           0           0           0   
4           2           0           0           0           0           0   

   cluster_36  cluster_37  cluster_38  cluster_39  cluster_40  cluster_41  \
0           7           1           0           0           7           1   
1           7           1           0           0           7           1   
2           7           1           0           0           7           1   
3           7           1           0           0           7           1   
4           7           1           0           0           7           1   

   cluster_42  cluster_43  cluster_44  cluster_45  cluster_46  cluster_47  \
0           2           1           0           0           1           0   
1           2           1           0           0           1           0   
2           2           1           0           0           1           0   
3           1           1           0           0           1           0   
4           1           1           0           0           1           0   

   cluster_48  cluster_49  cluster_50  cluster_51  cluster_52  cluster_53  \
0           0           0           0           0           1           0   
1           0           0           0           0           1           0   
2           0           0           0           0           1           0   
3           0           0           0           0  

In [7]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

train['label'] = le.fit_transform(train['label'])
train['filename'] = le.fit_transform(train['filename'])

test['label'] = le.fit_transform(test['label'])
test['filename'] = le.fit_transform(test['filename'])

In [8]:
def train_test(train_file, test_file):
        
    X_train= train.drop(columns = ['label'])
    y_train=train.loc[:,'label']
    
    X_test= test.drop(columns = ['label'])
    y_test=test.loc[:,'label']
    return X_train,y_train.values,X_test,y_test.values

In [9]:
x_train,y_train,x_test,y_test = train_test(train,test)


In [10]:
x_train = x_train[x_test.columns]

In [11]:
print(x_train.shape,y_train.shape,x_test.shape,y_test.shape)

(143835, 249) (143835,) (35884, 249) (35884,)


In [ ]:
lr = LogisticRegression()
lr.fit(x_train, y_train)

In [90]:
pred = lr.predict(x_train)
lr_report = pd.DataFrame(classification_report(y_train, pred, output_dict=True))
print("Train Result:\n================================================")
print(f"Accuracy Score: {accuracy_score(y_train, pred) * 100:.2f}%")
print("_______________________________________________")
print(f"CLASSIFICATION REPORT:\n{lr_report}")
print("_______________________________________________")
print(f"Confusion Matrix: \n {confusion_matrix(y_train, pred)}\n")
print("_______________________________________________")
print(f'Recall Score: \n {recall_score(y_train, pred)}')
print("_______________________________________________")
print(f'Roc AUC Score: \n {roc_auc_score(y_train, pred)}')

Train Result:
Accuracy Score: 86.63%
_______________________________________________
CLASSIFICATION REPORT:
                 0              1  accuracy      macro avg   weighted avg
precision      0.0       0.866340   0.86634       0.433170       0.750545
recall         0.0       1.000000   0.86634       0.500000       0.866340
f1-score       0.0       0.928384   0.86634       0.464192       0.804296
support    19225.0  124610.000000   0.86634  143835.000000  143835.000000
_______________________________________________
Confusion Matrix: 
 [[     0  19225]
 [     0 124610]]

_______________________________________________
Recall Score: 
 1.0
_______________________________________________
Roc AUC Score: 
 0.5


In [91]:
pred = lr.predict(x_test)
lr_report = pd.DataFrame(classification_report(y_test, pred, output_dict=True))
print("Test Result:\n================================================")        
print(f"Accuracy Score: {accuracy_score(y_test, pred) * 100:.2f}%")
print("_______________________________________________")
print(f"CLASSIFICATION REPORT:\n{lr_report}")
print("_______________________________________________")
print(f"Confusion Matrix: \n {confusion_matrix(y_test, pred)}\n")
print("_______________________________________________")
print(f'Recall Score: \n {recall_score(y_test, pred)}')
print("_______________________________________________")
print(f'Roc AUC Score: \n {roc_auc_score(y_test, pred)}')

Test Result:
Accuracy Score: 86.82%
_______________________________________________
CLASSIFICATION REPORT:
                0             1  accuracy     macro avg  weighted avg
precision     0.0      0.868186  0.868186      0.434093      0.753748
recall        0.0      1.000000  0.868186      0.500000      0.868186
f1-score      0.0      0.929443  0.868186      0.464722      0.806930
support    4730.0  31154.000000  0.868186  35884.000000  35884.000000
_______________________________________________
Confusion Matrix: 
 [[    0  4730]
 [    0 31154]]

_______________________________________________
Recall Score: 
 1.0
_______________________________________________
Roc AUC Score: 
 0.5


In [92]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

scaled_data = scaler.fit_transform(X)
scaled_data

array([[-0.29758974, -0.14496089, -0.87943614, ..., -0.04919487,
        -0.9450698 , -1.73571639],
       [-0.29758974, -0.14496089, -0.87943614, ..., -0.0491953 ,
        -0.9450698 , -1.73571639],
       [-0.29758974, -0.14496089, -0.87943614, ..., -0.04925357,
        -0.9450698 , -1.73571639],
       ...,
       [-0.29758974, -0.14496089, -0.87943614, ..., -0.04702967,
         2.34747091,  1.68213354],
       [-0.29758974, -0.14496089, -0.87943614, ..., -0.04709095,
         2.34747368,  1.51937878],
       [-0.29758974, -0.14496089, -0.87943614, ..., -0.04707681,
         2.34747516,  1.51937878]])

In [93]:
x_train,x_test,y_train,y_test = train_test_split(scaled_data,y,test_size=0.3,random_state=42)

In [94]:
lr = LogisticRegression()
lr.fit(x_train, y_train)

LogisticRegression()

In [95]:
pred = lr.predict(x_train)
lr_report = pd.DataFrame(classification_report(y_train, pred, output_dict=True))
print("Train Result:\n================================================")
print(f"Accuracy Score: {accuracy_score(y_train, pred) * 100:.2f}%")
print("_______________________________________________")
print(f"CLASSIFICATION REPORT:\n{lr_report}")
print("_______________________________________________")
print(f"Confusion Matrix: \n {confusion_matrix(y_train, pred)}\n")
print("_______________________________________________")
print(f'Recall Score: \n {recall_score(y_train, pred)}')
print("_______________________________________________")
print(f'Roc AUC Score: \n {roc_auc_score(y_train, pred)}')

Train Result:
Accuracy Score: 90.32%
_______________________________________________
CLASSIFICATION REPORT:
                      0             1  accuracy      macro avg   weighted avg
precision      0.718798      0.920044  0.903212       0.819421       0.893200
recall         0.450707      0.972861  0.903212       0.711784       0.903212
f1-score       0.554025      0.945715  0.903212       0.749870       0.893469
support    13430.000000  87254.000000  0.903212  100684.000000  100684.000000
_______________________________________________
Confusion Matrix: 
 [[ 6053  7377]
 [ 2368 84886]]

_______________________________________________
Recall Score: 
 0.9728608430559057
_______________________________________________
Roc AUC Score: 
 0.7117841073060616


In [96]:
pred = lr.predict(x_test)
lr_report = pd.DataFrame(classification_report(y_test, pred, output_dict=True))
print("Test Result:\n================================================")        
print(f"Accuracy Score: {accuracy_score(y_test, pred) * 100:.2f}%")
print("_______________________________________________")
print(f"CLASSIFICATION REPORT:\n{lr_report}")
print("_______________________________________________")
print(f"Confusion Matrix: \n {confusion_matrix(y_test, pred)}\n")
print("_______________________________________________")
print(f'Recall Score: \n {recall_score(y_test, pred)}')
print("_______________________________________________")
print(f'Roc AUC Score: \n {roc_auc_score(y_test, pred)}')

Test Result:
Accuracy Score: 90.21%
_______________________________________________
CLASSIFICATION REPORT:
                     0             1  accuracy     macro avg  weighted avg
precision     0.712968      0.919752  0.902088      0.816360      0.891981
recall        0.453494      0.971678  0.902088      0.712586      0.902088
f1-score      0.554372      0.945002  0.902088      0.749687      0.892542
support    5795.000000  37356.000000  0.902088  43151.000000  43151.000000
_______________________________________________
Confusion Matrix: 
 [[ 2628  3167]
 [ 1058 36298]]

_______________________________________________
Recall Score: 
 0.971677909840454
_______________________________________________
Roc AUC Score: 
 0.7125861507787257
